### ISSUE TITLE
The README instructions for advanced use are incorrect, resulting in the config being ignored

### ISSUE THREAD

**Issue by grempe** [Quasibit/eleventy-plugin-sitemap#2]
In the following sections of the README the usage instructions are incorrect:

https://github.com/quasibit/eleventy-plugin-sitemap#advanced-usage
https://github.com/quasibit/eleventy-plugin-sitemap#exclude-pages-from-the-sitemap

The example provided:

```
---
sitemap:
  - changefreq: weekly
  - priority: 0.8
---
```

Should actually be:

```
---
sitemap:
  changefreq: weekly
  priority: 0.8
---
```

The extra `-` change `sitemap` into an array of items which is not what the upstream sitemap lib expects. It expects `changefreq` and `priority` to be added as keys on an Object.

Without this change no changefreq or priority values are written into the generated `sitemap.xml`.

It might also be helpful to document how this config can be applied to a folder of items using e.g. `blog.11tydata.js` like:

```
module.exports = () => {
  return {
    layout: "post",
    tags: ["post"],
    sitemap: {
      changefreq: "weekly",
      priority: 0.8,
    },
  }
}
```

**Comment by nunof07** [comment]
Hi @grempe , thank you for reporting this. I've updated the README and added some examples.

https://github.com/quasibit/eleventy-plugin-sitemap/pull/3/files
