### ISSUE TITLE
Closing xml tag not being generated.

### ISSUE THREAD

**Issue by jaunt** [Quasibit/eleventy-plugin-sitemap#34]
My config is

```
  eleventyConfig.addPlugin(sitemap, {
    sitemap: {
      hostname: hostname,
    },
  });
```
And my sitemap file is

```
---
permalink: /sitemap.xml
layout: null
eleventyExcludeFromCollections: true
---
{% sitemap collections.all %}
```

The result looks great except for it's missing the closing XML tag.  Like this

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
	xmlns:xhtml="http://www.w3.org/1999/xhtml"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
	<url>
		...
	</url>
        ...
</urlset>
```

Any ideas what would cause the missing xml close tag?

**Comment by nunof07** [comment]
Hi @jaunt .

I don't see anything wrong in your example. What do you mean, missing xml close tag?

The `<?xml ?>` doesn't need closing, if that's what you mean.

**Comment by jaunt** [comment]
Wow, how embarrassing! Sorry about that.  Google was complaining about an error in my site map but now I think it's because there is a blank line at the top of it for some reason.  I naively assumed it was to do with the format.

**Comment by nunof07** [comment]
No worries! Glad you figured it out.
