### ISSUE TITLE
How to exclude specific files

### ISSUE THREAD

**Issue by ornelasnarciso** [Quasibit/eleventy-plugin-sitemap#35]
Hello.

How do i exclude specific files from the sitemap, that don't have front matter, like "footer"? 

Thanks.

**Comment by nunof07** [comment]
See https://github.com/quasibit/eleventy-plugin-sitemap#exclude-pages-from-the-sitemap

You can add data to a file through several ways: https://www.11ty.dev/docs/data-cascade/

**Comment by ornelasnarciso** [comment]
I have no idea how to use that information since there's no example to follow. (self taught programmer)
