### ISSUE TITLE
[Question] Add custom URLs to the sitemap

### ISSUE THREAD

**Issue by lazio** [Quasibit/eleventy-plugin-sitemap#37]
Hey @nunof07, thanks for the awesome plugin. 
I have a question about extending my sitemap with URLs from outside of my collections.all

Not sure it's best way to do that, but here is what I made.
`sitemap.11ty.js`:
```
module.exports = class {
  data() {
    return {
      layout: null,
      eleventyExcludeFromCollections: true,
      permalink: '/sitemap.xml',
    };
  }

  async render(data) {
    // save custom pages to array
    const customPages = [
      { url: '/innerUrl/pageOne/' },
      { url: '/innerUrl/pageTwo/' },
    ];
    // get URLs from collections.all
    const siteUrls = data.collections.all.map((item) => ({ url: item.url }));
    const sitemapUrls = siteUrls.concat(customPages);
    
    return await this.sitemap(sitemapUrls);
  }
};
```

this code is kinda working, but it's incredibly slow. My build is stuck on a step `Writing build/sitemap.xml from ./src/sitemap.11ty.js.` for more than 5 minutes before it's moving on. As I have a list of ~30 URLs, so it's too much for sitemap generation. 

Can you help me to understand what am I doing wrong?

**Comment by nunof07** [comment]
Hi @lazio .

No idea why it's so slow. Do you have a repo I can check?

You might also want to try [creating a custom collection](https://www.11ty.dev/docs/collections/#advanced-custom-filtering-and-sorting), but the result should be similar.

**Comment by lazio** [comment]
Hi @nunof07 , sorry for delay, my colleague already fixed the issue by moving the logic to the `.eleventy.js`:
```
  config.addCollection('sitemap', (api) =>
     api
       .getAll()
       .concat([
         { url: '/innerUrl/pageOne/' },
         { url: '/innerUrl/pageTwo/' },
       ])
   );
```

and using this collection in `sitemap.html`
```
{% sitemap collections.sitemap %}
```

thanks for your willingness to help.

**Comment by nunof07** [comment]
Glad you found a solution and thanks for the update.
