### ISSUE TITLE
eleventyComputed value for sitemap.ignore

### ISSUE THREAD

**Issue by edhenderson** [Quasibit/eleventy-plugin-sitemap#48]
I am pulling data in from Contenful. All works fine, I can render data onto the page and the correct values appear. My problem is with pushing this data through to your Site Map. Please can you see if this is something dumb on my part. I have a boolean field called `includeInSiteMap`.

```
---
layout: contained.njk
pagination:
  data: dunbar
  size: 1
  alias: dunbarPage
permalink: "{{ dunbarPage.slug | safeSlug }}"
eleventyComputed:
  sitemap:
    ignore: "{{ not dunbarPage.includeInSiteMap }}"
---
:
<h3>{{ not dunbarPage.includeInSiteMap }}</h3>
```

The value in the `h3` is always reflective of the value passed in, however the sitemap is not. If I hardwire `true` or `false` in the `sitemap.ignore` line it works absolutely fine.

Its *like* its building the Site Map before the value is resolved in the Front Matter. Any clues would be appreciated, thank you so much.

**Comment by nunof07** [comment]
Hi @edhenderson , the problem, as far as I can see, is that the ignore property is being set as a string (`"true"`/`"false"`) instead of boolean.

You can see a similar complain here, but for a core property: https://github.com/11ty/eleventy/issues/2079

The solution would be to use JS frontmatter/data file or create a custom collection.

**Comment by edhenderson** [comment]
@nunof07 Thanks for your time and advice. I will take a look ASAP.

**Comment by edhenderson** [comment]
I tried same as above but this time removing quotes:

```
:
:
eleventyComputed:
  sitemap:
    ignore: {{ not dunbarPage.includeInSiteMap }}
:
:
```

but it still no worky. I will try converting to JS front matter (new to me) and see if that helps.

**Comment by edhenderson** [comment]
So I switched to 

```
---js
{
  layout: 'contained.njk',
  pagination: {
    data: 'dunbar',
    size: 1,
    alias: 'dunbarPage'
  },
  permalink: "{{ dunbarPage.slug | safeSlug }}",
  eleventyComputed: {
    sitemap: {
      ignore(data) {
        if (data && data.dunbarPage && data.dunbarPage.hasOwnProperty('includeInSiteMap')) {
          console.log('YES');
          console.log('!data.dunbarPage.includeInSiteMap', !data.dunbarPage.includeInSiteMap);
          return !data.dunbarPage.includeInSiteMap;
        }
        console.log('NO');
        return undefined;
      }
    }
  }
}
---
```

and I have one page. This is the output I get:


```
NO
YES
!data.dunbarPage.includeInSiteMap false
```

The function seems to be called twice. Regardless of what I set the `includeInSiteMap` too, the value is ignored. The `undefined` seems to take precedence? If I hardwire `true` or `false` in here, it works. Any ideas?

**Comment by nunof07** [comment]
@edhenderson it seems like the value of `!data.dunbarPage.includeInSiteMap` is `false` in your example. It's hard to say what's going wrong without a reproduction.

This is what I have and it works well:

File `post_ignore.11tydata.json`:
```
{
  "myCustomIgnore": true
}
```


File `post_ignore.md`:
```
---js
{
  eleventyComputed: {
    sitemap: {
      ignore(data) {
        console.log(data);
        return data && data.myCustomIgnore;
      }
    }
  }
}
---

# Post Ignore

This post should be ignored in the sitemap.

Test: {{ myCustomIgnore }}
```

**Comment by edhenderson** [comment]
Thank you so much for taking the time to follow up on this, very much appreciated. I will endeavour to to investigate this further in the next few days, cheers.

**Comment by edhenderson** [comment]
Here is what I have in `dunbar-pages.njk`:

```js
{
  layout: "contained.njk",
  pagination: {
    data: "dunbar",
    size: 1,
    alias: "dunbarPage"
  },
  permalink: "{{ dunbarPage.slug | safeSlug }}",
  eleventyComputed: {
    sitemap: {
      ignore(data) {
        const ignore = data && data.dunbarPage && !data.dunbarPage.includeInSiteMap;
        console.log(data.dunbarPage.title, 'ignore', ignore);
        return ignore;
      }
    },
  }
}
```

I have 4 pages, 3 are normal with `includeInSiteMap` set to `true` but _Flux Capacitor_ has `includeInSiteMap` set to `false`.

When I build my site I get:

```
Flux Capacitor ignore true
Flux Capacitor ignore true
Transportation ignore false
Transportation ignore false
Construction ignore false
Construction ignore false
Hospitality ignore false
Hospitality ignore false
```

These values are correct. `ignore` should be `true` for the _Flux Capacitor_ page. When I check `sitemap.xml` however, none of the pages are included.

If I hardwire the `return` statement to `false`, all 4 pages are included in `sitemap.xml`, if I hardwire `true`, none of them are included.

You can see my confusion.

**Comment by nunof07** [comment]
@edhenderson it's very weird, indeed. Can you setup a small reproduction that I can check? Also share your sitemap template please.

**Comment by edhenderson** [comment]
@nunof07 I'll need to setup a repro, will do that as soon as I can. My template is:

```
---
permalink: /sitemap.xml
layout: null
eleventyExcludeFromCollections: true
---
{% sitemap collections.all %}
```

**Comment by nunof07** [comment]
Thanks @edhenderson .

The template looks good.
You can also try creating a custom collection with the items already ignored and using that for the sitemap.

**Comment by edhenderson** [comment]
So solution was as follows:

Template

```njk
---
permalink: /sitemap.xml
layout: null
eleventyExcludeFromCollections: true
---
{% sitemap collections.dunbarSitemap %}
```

Then JS to build collection (dunbar is the data returned from Contentful):

```js
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  eleventyConfig.addCollection('dunbarSitemap', function(collectionApi) {

    const rawDunbarItems = collectionApi.getAll()[0].data.dunbar; // 🤮
    const cookedDunbarItems = rawDunbarItems
      .filter((item) => {
        return item.includeInSiteMap;
      })
      .map((item) => ({
        url: item.slug,
        date: item.updatedDate
      }))
    ;

    const rawAllItems = collectionApi.getAll();
    const cookedAllItems = rawAllItems
      .filter((item) => {
        // 🤮
        if (item
          && 'data' in item
          && 'sitemap' in item.data
          && 'ignore' in item.data.sitemap
        ) {
          return !item.data.sitemap.ignore;
        }
        // Assume good if we make it this far. God speed little page.
        return true;
      })
    .map((item) => ({
      url: item.url,
      date: item.date
    }));

    return [...cookedDunbarItems, ...cookedAllItems];

  });
```

**Comment by edhenderson** [comment]
Basically a combo of both the Contentful data and the existing 11ty data. Custom collection was the way to go, thank you for your help.

**Comment by nunof07** [comment]
Thanks for the follow up @edhenderson .
