### ISSUE TITLE
Multilingual sitemap not rendered correctly

### ISSUE THREAD

**Issue by xplosionmind** [Quasibit/eleventy-plugin-sitemap#49]
I have implemented this plugin on my website, and the sitemap is correctly generated. Nevertheless, no alternate links are working.

1. [I installed the plugin and configured it](https://github.com/xplosionmind/tommi.space/blob/cd43ff28d914b8bd1c489f347d2a45de7d75a9af/.eleventy.js#L174)
2. [I set the default `lang` as `en`](https://github.com/xplosionmind/tommi.space/blob/main/content/content.11tydata.json), for all pages. Doing so, I would need to specify only languages ≠ `en`
3. [I created the custom collection](https://github.com/xplosionmind/tommi.space/blob/cd43ff28d914b8bd1c489f347d2a45de7d75a9af/.eleventy.js#L93), only [changing `translationKey` with `ref`](https://github.com/xplosionmind/tommi.space/blob/cd43ff28d914b8bd1c489f347d2a45de7d75a9af/.eleventy.js#L107)
4. I created [`sitemap.njk`](https://github.com/xplosionmind/tommi.space/blob/main/sitemap.njk), but…
5. …[`https://tommi.space/sitemap.xml`](https://tommi.space/sitemap.xml 'sitemap of tommi.space') contains **no `alternate` pages**.

What am I doing wrong?

**Thanks a lot** in advance!

Best,  
Tommi

**Comment by nunof07** [comment]
Hi @xplosionmind ,

`sitemap.njk` must point to the new collection:

```
---
permalink: /sitemap.xml
layout: ~
eleventyExcludeFromCollections: true
---
{% sitemap collections.sitemap %}
```

**Comment by xplosionmind** [comment]
> `sitemap.njk` must point to the new collection

You are right! How mindless of me… Thanks a lot!
