### ISSUE TITLE
How to automatically detect the page image

### ISSUE THREAD

**Issue by xplosionmind** [Quasibit/eleventy-plugin-sitemap#52]
Currently, the plugin natively supports no image linking. In my website, in the front matter of some pages I have an `image` string, containing its URL. Otherwise, I set [a default fallback image](https://github.com/xplosionmind/tommi.space/blob/ccdb9a85f4df0ae9f700e7e935e1f01d363d25c0/content/content.11tydata.js#L11). By doing so, I always have an image URL when using `{{ image }}` within each and every template.

How can I make this plugin recognize the image? If I use:
```
// tommi.space/content/content.11tydata.js
module.exports = {
  sitemap {
    img {
      url: '{{ image }}'
    }
  }
}
```

…it is printed `https://tommi.space/%7B%7B%20image%20%7D%7D` in the sitemap.

Could you help me? Thanks a lot! ❤️

**Comment by nunof07** [comment]
Hi @xplosionmind , try using computed data. Instead of using a template string, use a callback and access the data variable directly.

**Comment by xplosionmind** [comment]
> use a callback and access the data variable directly.

Thanks a lot! I am sorry I do not know how to use it (I am still wrapping my head around JavaScript…) could you be so kind to provide a basic example? I will work on that and publish here what I developed.

Thanks again!

**Comment by nunof07** [comment]
@xplosionmind can you try this:

```
module.exports = {
  eleventyComputed: {
    sitemap: {
      img: data => {
        return { url: data.image };
      },
    },
  },
};
```

More info about computed data here: https://www.11ty.dev/docs/data-computed/#using-javascript

**Comment by xplosionmind** [comment]
> can you try this

The result I get for the image url is `https://tommi.space/undefined`. I fear this does not work 🤔

**Comment by xplosionmind** [comment]
It works! This is awesome. Thanks a lot, @nunof07!
