### ISSUE TITLE
Include in sitemap even if not in `collections.all`

### ISSUE THREAD

**Issue by xplosionmind** [Quasibit/eleventy-plugin-sitemap#73]
I have a problem with Eleventy pages generation, and I really need to exclude from all collections my homepage. Nevertheless, by doing so, it gets excluded from the sitemap. It would be great to add support for:

```
sitemap:
  ignore: false
```

…in order to bypass `eleventyExcludeFromCollections: true`

**Comment by nunof07** [comment]
The problem is that you have to pass a collection to the sitemap. If you are excluding the item from all collections, then it is already filtered out by the time it reaches the sitemap shortcode, so the property won't have any effect.

For your use case, I suggest trying a custom collection.

**Comment by xplosionmind** [comment]
Thanks a lot. I figured it would be a mess.
